// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: ordo.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service status
type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN     HealthResponse_Status = 0
	HealthResponse_SERVING     HealthResponse_Status = 1
	HealthResponse_NOT_SERVING HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_ordo_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_ordo_proto_enumTypes[0]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{20, 0}
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the ruleset to execute
	RulesetName string `protobuf:"bytes,1,opt,name=ruleset_name,json=rulesetName,proto3" json:"ruleset_name,omitempty"`
	// Input data as JSON string
	InputJson string `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	// Whether to include execution trace in response
	IncludeTrace  bool `protobuf:"varint,3,opt,name=include_trace,json=includeTrace,proto3" json:"include_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_ordo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetRulesetName() string {
	if x != nil {
		return x.RulesetName
	}
	return ""
}

func (x *ExecuteRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ExecuteRequest) GetIncludeTrace() bool {
	if x != nil {
		return x.IncludeTrace
	}
	return false
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Execution result code (e.g., "APPROVED", "REJECTED")
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable result message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Output data as JSON string
	OutputJson string `protobuf:"bytes,3,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	// Execution duration in microseconds
	DurationUs uint64 `protobuf:"varint,4,opt,name=duration_us,json=durationUs,proto3" json:"duration_us,omitempty"`
	// Execution trace (if requested)
	Trace         *ExecutionTrace `protobuf:"bytes,5,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_ordo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteResponse) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *ExecuteResponse) GetDurationUs() uint64 {
	if x != nil {
		return x.DurationUs
	}
	return 0
}

func (x *ExecuteResponse) GetTrace() *ExecutionTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

type ExecutionTrace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path of step IDs taken during execution
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Details of each step executed
	Steps         []*StepTrace `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionTrace) Reset() {
	*x = ExecutionTrace{}
	mi := &file_ordo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionTrace) ProtoMessage() {}

func (x *ExecutionTrace) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionTrace.ProtoReflect.Descriptor instead.
func (*ExecutionTrace) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionTrace) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExecutionTrace) GetSteps() []*StepTrace {
	if x != nil {
		return x.Steps
	}
	return nil
}

type BatchExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the ruleset to execute
	RulesetName string `protobuf:"bytes,1,opt,name=ruleset_name,json=rulesetName,proto3" json:"ruleset_name,omitempty"`
	// List of inputs as JSON strings
	InputsJson []string `protobuf:"bytes,2,rep,name=inputs_json,json=inputsJson,proto3" json:"inputs_json,omitempty"`
	// Execution options
	Options       *BatchExecuteOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchExecuteRequest) Reset() {
	*x = BatchExecuteRequest{}
	mi := &file_ordo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExecuteRequest) ProtoMessage() {}

func (x *BatchExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExecuteRequest.ProtoReflect.Descriptor instead.
func (*BatchExecuteRequest) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{3}
}

func (x *BatchExecuteRequest) GetRulesetName() string {
	if x != nil {
		return x.RulesetName
	}
	return ""
}

func (x *BatchExecuteRequest) GetInputsJson() []string {
	if x != nil {
		return x.InputsJson
	}
	return nil
}

func (x *BatchExecuteRequest) GetOptions() *BatchExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type BatchExecuteOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to execute in parallel (default: true)
	Parallel bool `protobuf:"varint,1,opt,name=parallel,proto3" json:"parallel,omitempty"`
	// Whether to include execution trace in results (default: false)
	IncludeTrace  bool `protobuf:"varint,2,opt,name=include_trace,json=includeTrace,proto3" json:"include_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchExecuteOptions) Reset() {
	*x = BatchExecuteOptions{}
	mi := &file_ordo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExecuteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExecuteOptions) ProtoMessage() {}

func (x *BatchExecuteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExecuteOptions.ProtoReflect.Descriptor instead.
func (*BatchExecuteOptions) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{4}
}

func (x *BatchExecuteOptions) GetParallel() bool {
	if x != nil {
		return x.Parallel
	}
	return false
}

func (x *BatchExecuteOptions) GetIncludeTrace() bool {
	if x != nil {
		return x.IncludeTrace
	}
	return false
}

type BatchExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Results for each input (in same order as inputs)
	Results []*BatchExecuteResultItem `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Summary statistics
	Summary       *BatchExecuteSummary `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchExecuteResponse) Reset() {
	*x = BatchExecuteResponse{}
	mi := &file_ordo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExecuteResponse) ProtoMessage() {}

func (x *BatchExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExecuteResponse.ProtoReflect.Descriptor instead.
func (*BatchExecuteResponse) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{5}
}

func (x *BatchExecuteResponse) GetResults() []*BatchExecuteResultItem {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchExecuteResponse) GetSummary() *BatchExecuteSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type BatchExecuteResultItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Execution result code (e.g., "APPROVED", "REJECTED", or "error" if failed)
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable result message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Output data as JSON string
	OutputJson string `protobuf:"bytes,3,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	// Execution duration in microseconds
	DurationUs uint64 `protobuf:"varint,4,opt,name=duration_us,json=durationUs,proto3" json:"duration_us,omitempty"`
	// Execution trace (if requested)
	Trace *ExecutionTrace `protobuf:"bytes,5,opt,name=trace,proto3" json:"trace,omitempty"`
	// Error message (if failed)
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchExecuteResultItem) Reset() {
	*x = BatchExecuteResultItem{}
	mi := &file_ordo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExecuteResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExecuteResultItem) ProtoMessage() {}

func (x *BatchExecuteResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExecuteResultItem.ProtoReflect.Descriptor instead.
func (*BatchExecuteResultItem) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{6}
}

func (x *BatchExecuteResultItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BatchExecuteResultItem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchExecuteResultItem) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *BatchExecuteResultItem) GetDurationUs() uint64 {
	if x != nil {
		return x.DurationUs
	}
	return 0
}

func (x *BatchExecuteResultItem) GetTrace() *ExecutionTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *BatchExecuteResultItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchExecuteSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of inputs
	Total uint32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Number of successful executions
	Success uint32 `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Number of failed executions
	Failed uint32 `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	// Total execution time in microseconds (sum of all individual durations)
	TotalDurationUs uint64 `protobuf:"varint,4,opt,name=total_duration_us,json=totalDurationUs,proto3" json:"total_duration_us,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchExecuteSummary) Reset() {
	*x = BatchExecuteSummary{}
	mi := &file_ordo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExecuteSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExecuteSummary) ProtoMessage() {}

func (x *BatchExecuteSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExecuteSummary.ProtoReflect.Descriptor instead.
func (*BatchExecuteSummary) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{7}
}

func (x *BatchExecuteSummary) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BatchExecuteSummary) GetSuccess() uint32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *BatchExecuteSummary) GetFailed() uint32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchExecuteSummary) GetTotalDurationUs() uint64 {
	if x != nil {
		return x.TotalDurationUs
	}
	return 0
}

type StepTrace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Step ID
	StepId string `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Step name
	StepName string `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	// Step duration in microseconds
	DurationUs uint64 `protobuf:"varint,3,opt,name=duration_us,json=durationUs,proto3" json:"duration_us,omitempty"`
	// Step result (for decision steps: "true"/"false", for terminal: "terminal")
	Result        string `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepTrace) Reset() {
	*x = StepTrace{}
	mi := &file_ordo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepTrace) ProtoMessage() {}

func (x *StepTrace) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepTrace.ProtoReflect.Descriptor instead.
func (*StepTrace) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{8}
}

func (x *StepTrace) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepTrace) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepTrace) GetDurationUs() uint64 {
	if x != nil {
		return x.DurationUs
	}
	return 0
}

func (x *StepTrace) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GetRuleSetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the ruleset
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleSetRequest) Reset() {
	*x = GetRuleSetRequest{}
	mi := &file_ordo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleSetRequest) ProtoMessage() {}

func (x *GetRuleSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleSetRequest.ProtoReflect.Descriptor instead.
func (*GetRuleSetRequest) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{9}
}

func (x *GetRuleSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRuleSetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RuleSet definition as JSON
	RulesetJson string `protobuf:"bytes,1,opt,name=ruleset_json,json=rulesetJson,proto3" json:"ruleset_json,omitempty"`
	// Version of the ruleset
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Number of steps in the ruleset
	StepCount     uint32 `protobuf:"varint,4,opt,name=step_count,json=stepCount,proto3" json:"step_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleSetResponse) Reset() {
	*x = GetRuleSetResponse{}
	mi := &file_ordo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleSetResponse) ProtoMessage() {}

func (x *GetRuleSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleSetResponse.ProtoReflect.Descriptor instead.
func (*GetRuleSetResponse) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{10}
}

func (x *GetRuleSetResponse) GetRulesetJson() string {
	if x != nil {
		return x.RulesetJson
	}
	return ""
}

func (x *GetRuleSetResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetRuleSetResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetRuleSetResponse) GetStepCount() uint32 {
	if x != nil {
		return x.StepCount
	}
	return 0
}

type ListRuleSetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by prefix
	NamePrefix string `protobuf:"bytes,1,opt,name=name_prefix,json=namePrefix,proto3" json:"name_prefix,omitempty"`
	// Maximum number of results (0 = no limit)
	Limit         uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleSetsRequest) Reset() {
	*x = ListRuleSetsRequest{}
	mi := &file_ordo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleSetsRequest) ProtoMessage() {}

func (x *ListRuleSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleSetsRequest.ProtoReflect.Descriptor instead.
func (*ListRuleSetsRequest) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{11}
}

func (x *ListRuleSetsRequest) GetNamePrefix() string {
	if x != nil {
		return x.NamePrefix
	}
	return ""
}

func (x *ListRuleSetsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRuleSetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of ruleset summaries
	Rulesets []*RuleSetSummary `protobuf:"bytes,1,rep,name=rulesets,proto3" json:"rulesets,omitempty"`
	// Total count
	TotalCount    uint32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleSetsResponse) Reset() {
	*x = ListRuleSetsResponse{}
	mi := &file_ordo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleSetsResponse) ProtoMessage() {}

func (x *ListRuleSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleSetsResponse.ProtoReflect.Descriptor instead.
func (*ListRuleSetsResponse) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{12}
}

func (x *ListRuleSetsResponse) GetRulesets() []*RuleSetSummary {
	if x != nil {
		return x.Rulesets
	}
	return nil
}

func (x *ListRuleSetsResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type RuleSetSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RuleSet name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Number of steps
	StepCount     uint32 `protobuf:"varint,4,opt,name=step_count,json=stepCount,proto3" json:"step_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleSetSummary) Reset() {
	*x = RuleSetSummary{}
	mi := &file_ordo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSetSummary) ProtoMessage() {}

func (x *RuleSetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSetSummary.ProtoReflect.Descriptor instead.
func (*RuleSetSummary) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{13}
}

func (x *RuleSetSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleSetSummary) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RuleSetSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleSetSummary) GetStepCount() uint32 {
	if x != nil {
		return x.StepCount
	}
	return 0
}

type EvalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expression to evaluate
	Expression string `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	// Context data as JSON string
	ContextJson   string `protobuf:"bytes,2,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalRequest) Reset() {
	*x = EvalRequest{}
	mi := &file_ordo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalRequest) ProtoMessage() {}

func (x *EvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalRequest.ProtoReflect.Descriptor instead.
func (*EvalRequest) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{14}
}

func (x *EvalRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *EvalRequest) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

type EvalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result value as JSON
	ResultJson string `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// Parsed expression (for debugging)
	ParsedExpression string `protobuf:"bytes,2,opt,name=parsed_expression,json=parsedExpression,proto3" json:"parsed_expression,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EvalResponse) Reset() {
	*x = EvalResponse{}
	mi := &file_ordo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalResponse) ProtoMessage() {}

func (x *EvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalResponse.ProtoReflect.Descriptor instead.
func (*EvalResponse) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{15}
}

func (x *EvalResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *EvalResponse) GetParsedExpression() string {
	if x != nil {
		return x.ParsedExpression
	}
	return ""
}

type TypedExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the ruleset to execute
	RulesetName string `protobuf:"bytes,1,opt,name=ruleset_name,json=rulesetName,proto3" json:"ruleset_name,omitempty"`
	// Schema name for the context (must be registered on server)
	SchemaName string `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	// Context data as protobuf bytes
	// The server will decode this using the registered schema
	ContextBytes []byte `protobuf:"bytes,3,opt,name=context_bytes,json=contextBytes,proto3" json:"context_bytes,omitempty"`
	// Whether to include execution trace in response
	IncludeTrace  bool `protobuf:"varint,4,opt,name=include_trace,json=includeTrace,proto3" json:"include_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedExecuteRequest) Reset() {
	*x = TypedExecuteRequest{}
	mi := &file_ordo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedExecuteRequest) ProtoMessage() {}

func (x *TypedExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedExecuteRequest.ProtoReflect.Descriptor instead.
func (*TypedExecuteRequest) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{16}
}

func (x *TypedExecuteRequest) GetRulesetName() string {
	if x != nil {
		return x.RulesetName
	}
	return ""
}

func (x *TypedExecuteRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *TypedExecuteRequest) GetContextBytes() []byte {
	if x != nil {
		return x.ContextBytes
	}
	return nil
}

func (x *TypedExecuteRequest) GetIncludeTrace() bool {
	if x != nil {
		return x.IncludeTrace
	}
	return false
}

type TypedEvalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expression to evaluate
	Expression string `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	// Schema name for the context
	SchemaName string `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	// Context data as protobuf bytes
	ContextBytes  []byte `protobuf:"bytes,3,opt,name=context_bytes,json=contextBytes,proto3" json:"context_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedEvalRequest) Reset() {
	*x = TypedEvalRequest{}
	mi := &file_ordo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedEvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedEvalRequest) ProtoMessage() {}

func (x *TypedEvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedEvalRequest.ProtoReflect.Descriptor instead.
func (*TypedEvalRequest) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{17}
}

func (x *TypedEvalRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *TypedEvalRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *TypedEvalRequest) GetContextBytes() []byte {
	if x != nil {
		return x.ContextBytes
	}
	return nil
}

type TypedEvalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result value as f64 (all JIT results are numeric)
	Result float64 `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	// Whether JIT was used (true) or fell back to VM (false)
	JitUsed bool `protobuf:"varint,2,opt,name=jit_used,json=jitUsed,proto3" json:"jit_used,omitempty"`
	// Execution time in nanoseconds
	DurationNs    uint64 `protobuf:"varint,3,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedEvalResponse) Reset() {
	*x = TypedEvalResponse{}
	mi := &file_ordo_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedEvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedEvalResponse) ProtoMessage() {}

func (x *TypedEvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedEvalResponse.ProtoReflect.Descriptor instead.
func (*TypedEvalResponse) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{18}
}

func (x *TypedEvalResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TypedEvalResponse) GetJitUsed() bool {
	if x != nil {
		return x.JitUsed
	}
	return false
}

func (x *TypedEvalResponse) GetDurationNs() uint64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

type HealthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: specific service to check
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_ordo_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{19}
}

func (x *HealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=ordo.v1.HealthResponse_Status" json:"status,omitempty"`
	// Server version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Number of loaded rulesets
	RulesetCount uint32 `protobuf:"varint,3,opt,name=ruleset_count,json=rulesetCount,proto3" json:"ruleset_count,omitempty"`
	// Server uptime in seconds
	UptimeSeconds uint64 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_ordo_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordo_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_ordo_proto_rawDescGZIP(), []int{20}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetRulesetCount() uint32 {
	if x != nil {
		return x.RulesetCount
	}
	return 0
}

func (x *HealthResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_ordo_proto protoreflect.FileDescriptor

const file_ordo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ordo.proto\x12\aordo.v1\"w\n" +
	"\x0eExecuteRequest\x12!\n" +
	"\fruleset_name\x18\x01 \x01(\tR\vrulesetName\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\x12#\n" +
	"\rinclude_trace\x18\x03 \x01(\bR\fincludeTrace\"\xb0\x01\n" +
	"\x0fExecuteResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\voutput_json\x18\x03 \x01(\tR\n" +
	"outputJson\x12\x1f\n" +
	"\vduration_us\x18\x04 \x01(\x04R\n" +
	"durationUs\x12-\n" +
	"\x05trace\x18\x05 \x01(\v2\x17.ordo.v1.ExecutionTraceR\x05trace\"N\n" +
	"\x0eExecutionTrace\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12(\n" +
	"\x05steps\x18\x02 \x03(\v2\x12.ordo.v1.StepTraceR\x05steps\"\x91\x01\n" +
	"\x13BatchExecuteRequest\x12!\n" +
	"\fruleset_name\x18\x01 \x01(\tR\vrulesetName\x12\x1f\n" +
	"\vinputs_json\x18\x02 \x03(\tR\n" +
	"inputsJson\x126\n" +
	"\aoptions\x18\x03 \x01(\v2\x1c.ordo.v1.BatchExecuteOptionsR\aoptions\"V\n" +
	"\x13BatchExecuteOptions\x12\x1a\n" +
	"\bparallel\x18\x01 \x01(\bR\bparallel\x12#\n" +
	"\rinclude_trace\x18\x02 \x01(\bR\fincludeTrace\"\x89\x01\n" +
	"\x14BatchExecuteResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.ordo.v1.BatchExecuteResultItemR\aresults\x126\n" +
	"\asummary\x18\x02 \x01(\v2\x1c.ordo.v1.BatchExecuteSummaryR\asummary\"\xcd\x01\n" +
	"\x16BatchExecuteResultItem\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\voutput_json\x18\x03 \x01(\tR\n" +
	"outputJson\x12\x1f\n" +
	"\vduration_us\x18\x04 \x01(\x04R\n" +
	"durationUs\x12-\n" +
	"\x05trace\x18\x05 \x01(\v2\x17.ordo.v1.ExecutionTraceR\x05trace\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x89\x01\n" +
	"\x13BatchExecuteSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\rR\asuccess\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\rR\x06failed\x12*\n" +
	"\x11total_duration_us\x18\x04 \x01(\x04R\x0ftotalDurationUs\"z\n" +
	"\tStepTrace\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12\x1f\n" +
	"\vduration_us\x18\x03 \x01(\x04R\n" +
	"durationUs\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\"'\n" +
	"\x11GetRuleSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x92\x01\n" +
	"\x12GetRuleSetResponse\x12!\n" +
	"\fruleset_json\x18\x01 \x01(\tR\vrulesetJson\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"step_count\x18\x04 \x01(\rR\tstepCount\"L\n" +
	"\x13ListRuleSetsRequest\x12\x1f\n" +
	"\vname_prefix\x18\x01 \x01(\tR\n" +
	"namePrefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"l\n" +
	"\x14ListRuleSetsResponse\x123\n" +
	"\brulesets\x18\x01 \x03(\v2\x17.ordo.v1.RuleSetSummaryR\brulesets\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\"\x7f\n" +
	"\x0eRuleSetSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"step_count\x18\x04 \x01(\rR\tstepCount\"P\n" +
	"\vEvalRequest\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12!\n" +
	"\fcontext_json\x18\x02 \x01(\tR\vcontextJson\"\\\n" +
	"\fEvalResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\x12+\n" +
	"\x11parsed_expression\x18\x02 \x01(\tR\x10parsedExpression\"\xa3\x01\n" +
	"\x13TypedExecuteRequest\x12!\n" +
	"\fruleset_name\x18\x01 \x01(\tR\vrulesetName\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12#\n" +
	"\rcontext_bytes\x18\x03 \x01(\fR\fcontextBytes\x12#\n" +
	"\rinclude_trace\x18\x04 \x01(\bR\fincludeTrace\"x\n" +
	"\x10TypedEvalRequest\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12#\n" +
	"\rcontext_bytes\x18\x03 \x01(\fR\fcontextBytes\"g\n" +
	"\x11TypedEvalResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\x12\x19\n" +
	"\bjit_used\x18\x02 \x01(\bR\ajitUsed\x12\x1f\n" +
	"\vduration_ns\x18\x03 \x01(\x04R\n" +
	"durationNs\")\n" +
	"\rHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xe3\x01\n" +
	"\x0eHealthResponse\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.ordo.v1.HealthResponse.StatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12#\n" +
	"\rruleset_count\x18\x03 \x01(\rR\frulesetCount\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x04R\ruptimeSeconds\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\x9c\x03\n" +
	"\vOrdoService\x12<\n" +
	"\aExecute\x12\x17.ordo.v1.ExecuteRequest\x1a\x18.ordo.v1.ExecuteResponse\x12K\n" +
	"\fBatchExecute\x12\x1c.ordo.v1.BatchExecuteRequest\x1a\x1d.ordo.v1.BatchExecuteResponse\x12E\n" +
	"\n" +
	"GetRuleSet\x12\x1a.ordo.v1.GetRuleSetRequest\x1a\x1b.ordo.v1.GetRuleSetResponse\x12K\n" +
	"\fListRuleSets\x12\x1c.ordo.v1.ListRuleSetsRequest\x1a\x1d.ordo.v1.ListRuleSetsResponse\x123\n" +
	"\x04Eval\x12\x14.ordo.v1.EvalRequest\x1a\x15.ordo.v1.EvalResponse\x129\n" +
	"\x06Health\x12\x16.ordo.v1.HealthRequest\x1a\x17.ordo.v1.HealthResponseB8\n" +
	"\x11com.ordo.proto.v1P\x01Z!github.com/pama-lee/ordo/proto/v1b\x06proto3"

var (
	file_ordo_proto_rawDescOnce sync.Once
	file_ordo_proto_rawDescData []byte
)

func file_ordo_proto_rawDescGZIP() []byte {
	file_ordo_proto_rawDescOnce.Do(func() {
		file_ordo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ordo_proto_rawDesc), len(file_ordo_proto_rawDesc)))
	})
	return file_ordo_proto_rawDescData
}

var file_ordo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ordo_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_ordo_proto_goTypes = []any{
	(HealthResponse_Status)(0),     // 0: ordo.v1.HealthResponse.Status
	(*ExecuteRequest)(nil),         // 1: ordo.v1.ExecuteRequest
	(*ExecuteResponse)(nil),        // 2: ordo.v1.ExecuteResponse
	(*ExecutionTrace)(nil),         // 3: ordo.v1.ExecutionTrace
	(*BatchExecuteRequest)(nil),    // 4: ordo.v1.BatchExecuteRequest
	(*BatchExecuteOptions)(nil),    // 5: ordo.v1.BatchExecuteOptions
	(*BatchExecuteResponse)(nil),   // 6: ordo.v1.BatchExecuteResponse
	(*BatchExecuteResultItem)(nil), // 7: ordo.v1.BatchExecuteResultItem
	(*BatchExecuteSummary)(nil),    // 8: ordo.v1.BatchExecuteSummary
	(*StepTrace)(nil),              // 9: ordo.v1.StepTrace
	(*GetRuleSetRequest)(nil),      // 10: ordo.v1.GetRuleSetRequest
	(*GetRuleSetResponse)(nil),     // 11: ordo.v1.GetRuleSetResponse
	(*ListRuleSetsRequest)(nil),    // 12: ordo.v1.ListRuleSetsRequest
	(*ListRuleSetsResponse)(nil),   // 13: ordo.v1.ListRuleSetsResponse
	(*RuleSetSummary)(nil),         // 14: ordo.v1.RuleSetSummary
	(*EvalRequest)(nil),            // 15: ordo.v1.EvalRequest
	(*EvalResponse)(nil),           // 16: ordo.v1.EvalResponse
	(*TypedExecuteRequest)(nil),    // 17: ordo.v1.TypedExecuteRequest
	(*TypedEvalRequest)(nil),       // 18: ordo.v1.TypedEvalRequest
	(*TypedEvalResponse)(nil),      // 19: ordo.v1.TypedEvalResponse
	(*HealthRequest)(nil),          // 20: ordo.v1.HealthRequest
	(*HealthResponse)(nil),         // 21: ordo.v1.HealthResponse
}
var file_ordo_proto_depIdxs = []int32{
	3,  // 0: ordo.v1.ExecuteResponse.trace:type_name -> ordo.v1.ExecutionTrace
	9,  // 1: ordo.v1.ExecutionTrace.steps:type_name -> ordo.v1.StepTrace
	5,  // 2: ordo.v1.BatchExecuteRequest.options:type_name -> ordo.v1.BatchExecuteOptions
	7,  // 3: ordo.v1.BatchExecuteResponse.results:type_name -> ordo.v1.BatchExecuteResultItem
	8,  // 4: ordo.v1.BatchExecuteResponse.summary:type_name -> ordo.v1.BatchExecuteSummary
	3,  // 5: ordo.v1.BatchExecuteResultItem.trace:type_name -> ordo.v1.ExecutionTrace
	14, // 6: ordo.v1.ListRuleSetsResponse.rulesets:type_name -> ordo.v1.RuleSetSummary
	0,  // 7: ordo.v1.HealthResponse.status:type_name -> ordo.v1.HealthResponse.Status
	1,  // 8: ordo.v1.OrdoService.Execute:input_type -> ordo.v1.ExecuteRequest
	4,  // 9: ordo.v1.OrdoService.BatchExecute:input_type -> ordo.v1.BatchExecuteRequest
	10, // 10: ordo.v1.OrdoService.GetRuleSet:input_type -> ordo.v1.GetRuleSetRequest
	12, // 11: ordo.v1.OrdoService.ListRuleSets:input_type -> ordo.v1.ListRuleSetsRequest
	15, // 12: ordo.v1.OrdoService.Eval:input_type -> ordo.v1.EvalRequest
	20, // 13: ordo.v1.OrdoService.Health:input_type -> ordo.v1.HealthRequest
	2,  // 14: ordo.v1.OrdoService.Execute:output_type -> ordo.v1.ExecuteResponse
	6,  // 15: ordo.v1.OrdoService.BatchExecute:output_type -> ordo.v1.BatchExecuteResponse
	11, // 16: ordo.v1.OrdoService.GetRuleSet:output_type -> ordo.v1.GetRuleSetResponse
	13, // 17: ordo.v1.OrdoService.ListRuleSets:output_type -> ordo.v1.ListRuleSetsResponse
	16, // 18: ordo.v1.OrdoService.Eval:output_type -> ordo.v1.EvalResponse
	21, // 19: ordo.v1.OrdoService.Health:output_type -> ordo.v1.HealthResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ordo_proto_init() }
func file_ordo_proto_init() {
	if File_ordo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ordo_proto_rawDesc), len(file_ordo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ordo_proto_goTypes,
		DependencyIndexes: file_ordo_proto_depIdxs,
		EnumInfos:         file_ordo_proto_enumTypes,
		MessageInfos:      file_ordo_proto_msgTypes,
	}.Build()
	File_ordo_proto = out.File
	file_ordo_proto_goTypes = nil
	file_ordo_proto_depIdxs = nil
}
